solarwinds/apm-ruby

- test/api/opentelemetry_inspan_test.rb
- test/minitest_helper.rb
Attempt to fix the test case failure on solarwinds_apm wrapper on `in_span`
> NH-65512: try to fix the in_span issue

- .github/workflows/build_and_release_gem.yml
- CHANGELOG.md
- CONFIGURATION.md
- CONTRIBUTING.md
- lib/solarwinds_apm/support/swomarginalia/README.md
- lib/solarwinds_apm/support/swomarginalia/comment.rb
- lib/solarwinds_apm/support_report.rb
- solarwinds_apm.gemspec
Change `swotel-ruby` to `apm-ruby` and `solarwindscloud` to `solarwinds`
> NH-46957: update repo name and org name

- .github/workflows/build_for_github_package.yml
- Rakefile
- lib/solarwinds_apm/version.rb
- solarwinds_apm.gemspec
`secrets.GITHUB_TOKEN` seems having no permission to publish package; so we need new secrets, which I named `GH_PACKAGE_TOKEN`.
The package will be linked to repository after setting the metadata
> GitHub package upload

- CONFIGURATION.md
Some changes for the CONFIGURATION page while reviewing documentation website content.
> NH-69736 Docs fixup

- .github/dependabot.yml
> NH-66480: add dependabot.yml

- .gitignore
- lib/solarwinds_apm/otel_config.rb
- test/Dockerfile
- test/docker-compose.yml
- test/solarwinds_apm/otel_config_test.rb
1. sync sync sw logger and otel logger level if there is no `OTEL_LOG_LEVEL` present.
Standard test case that determine logger level based on `OTEL_LOG_LEVEL`.
> NH-70621: sync sw logger and otel logger

- lib/solarwinds_apm/version.rb
Version update.
Testbed testing passed. I think action/checkout@4 will fail on amazon linux but let's see what will happen.
> NH-70338: version-update

- .github/workflows/build_and_release_gem.yml
- Rakefile
Workflow update based on org change and github script change
> workflow update

- .github/workflows/verify_install.yml
Use arn for auth aws ec2
Test run: https://github.com/solarwinds/apm-ruby/actions/runs/8085409235
> NH-74149: use arn for auth aws ec2 

- .github/workflows/build_publish_lambda_layer.yml
> init file for lambda layer workflow

- lib/solarwinds_apm/version.rb
> ga-release

- CONFIGURATION.md
> NH-77720 one more update

- .github/workflows/build_and_release_gem.yml
- .github/workflows/scripts/verify_install.sh
- .github/workflows/verify_install.yml
- Rakefile
- lib/solarwinds_apm/version.rb
> NH-77720 ga release

- CHANGELOG.md
- CONFIGURATION.md
> NH-82532: update doc

- lib/solarwinds_apm/otel_lambda_config.rb
> NH-85975: update lambda layer log

- lib/solarwinds_apm/opentelemetry/otlp_processor.rb
- test/opentelemetry/otlp_processor_test.rb
- test/solarwinds_apm/oboe_metal_test.rb
> Lambda response mag

- CONFIGURATION.md
> NH-65373: add SW_APM_TRANSACTION_NAME to configuration.md

- lib/solarwinds_apm/constants.rb
Conform to https://opentelemetry.io/docs/specs/otel/common/mapping-to-non-otlp/ guideline on name.
> NH-89715 update trace attribute otel.status to otel.status_code

- lambda/otel/layer/Gemfile
- lambda/otel/layer/otel_wrapper.rb
- lib/solarwinds_apm/opentelemetry.rb
- lib/solarwinds_apm/otel_lambda_config.rb
Thanks again @xuan-cao-swi on making metrics exporter happen!
Build new lambda layer and run through manual tests.
> NH-89212 use upstream exporter

- .github/workflows/build_publish_lambda_layer.yml
- .gitignore
workflow: https://github.com/solarwinds/apm-ruby/actions/runs/10838011087
scanned result: (in reverse lab)
> NH-89340: add scan as part of build and publish lambda layer

- lambda/otel/layer/Gemfile
> lambda update

- Rakefile
- lib/solarwinds_apm/version.rb
> Release 6 1 2

- CONFIGURATION.md
Update to reflect latest released feature.
> Update tag_sql section

- Rakefile
- gemfiles/test_gems.gemfile
- lib/solarwinds_apm/support/resource_detector.rb
- lib/solarwinds_apm/support/resource_detector/aws/beanstalk.rb
- lib/solarwinds_apm/support/resource_detector/aws/ec2.rb
- lib/solarwinds_apm/support/resource_detector/aws/ecs.rb
- lib/solarwinds_apm/support/resource_detector/aws/eks.rb
- lib/solarwinds_apm/support/resource_detector/aws/lambda.rb
- test/minitest_helper.rb
- test/support/resource_detector/aws/beanstalk_test.rb
- test/support/resource_detector/aws/ec2_test.rb
- test/support/resource_detector/aws/ecs_test.rb
- test/support/resource_detector/aws/eks_test.rb
- test/support/resource_detector/aws/lambda_test.rb
- test/support/resource_detector/aws/sample_result.rb
- test/support/resource_detector_test.rb
Test case mainly cover for k8s and uams client. Test case for upstream detector is tricky, but upstream already have their own test case.
> NH-103815: add resource detector for k8s and uams client

- gemfiles/test_gems.gemfile
- lib/oboe_metal.rb
- lib/solarwinds_apm/oboe_init_options.rb
- lib/solarwinds_apm/opentelemetry/solarwinds_sampler.rb
- lib/solarwinds_apm/support/otlp_endpoint.rb
- lib/solarwinds_apm/support/service_key_checker.rb
- lib/solarwinds_apm/support/utils.rb
- test/minitest_helper.rb
- test/support/otlp_endpoint_test.rb
- test/test_setup.sh
> NH-105128: init add endpoint logic

- lib/solarwinds_apm/opentelemetry/otlp_processor.rb
- lib/solarwinds_apm/sampling/http_sampler.rb
- lib/solarwinds_apm/sampling/oboe_sampler.rb
- lib/solarwinds_apm/version.rb
> 7.0.0 prerelese 3
